[package]
name = "test_rust"
version = "0.1.0"
authors = ["Isaac Woods <isaac@isaacwoods.tk>"]

[dependencies]
libmessage = { path = "../libmessage" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
