language: rust
sudo: required
rust:
  - nightly

git:
  submodules: false

install:
  - sudo apt-get install nasm
  - sudo apt-get install grub2 grub2-common grub-common
  - sudo apt-get install xorriso
  - sudo apt-get install qemu-system
  - cargo install xargo
  - rustup component add rust-src

script:
  - GRUB_MKRESCUE=grub-mkrescue make
  # - qemu-system-x86_64 -vga=-nographic -smp 2 -usb -device usb-ehci,id=ehci --no-reboot -cdrom pebble.iso

notifications:
  email: false
