[package]
name = "heap_allocator"
version = "0.1.0"
authors = ["Isaac Woods <isaac@isaacwoods.tk>"]

[dependencies]
spin = "*"

[dependencies.log]
version                 = "*"
default-features        = false

[dependencies.common]
path = "../common"
