[workspace]

[package]
name = "rust_os"
version = "0.0.1"
authors = ["Isaac Woods"]

[lib]
crate-type = ["staticlib"]

[dependencies]
#rlibc       = "1.0"
#volatile    = "0.1.0"
#spin        = "0.4.5"
#multiboot2  = "0.3.2"
bitflags    = "*"
#bit_field   = "0.7.0"
#x86_64      = "0.1.2"
rlibc       = "*"
volatile    = "*"
spin        = "*"
multiboot2  = "*"
bit_field   = "*"
x86_64      = "*"

[dependencies.lazy_static]
version = "*"
features = ["spin_no_std"]

[dependencies.rustos_common]
path = "rustos_common"

[dependencies.hole_tracking_allocator]
path = "hole_tracking_allocator"
