[workspace]

[package]
name = "rust_os"
version = "0.0.1"
authors = ["Isaac Woods"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc       = "*"
volatile    = "*"
spin        = "*"
bitflags    = "*"
bit_field   = "*"

[dependencies.x86_64]
path = "x86_64"

[dependencies.util]
path = "util"
