[workspace]

[package]
name = "rust_os"
version = "0.0.1"
authors = ["Isaac Woods"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc       = "*"
volatile    = "*"
spin        = "*"
multiboot2  = "*"
bitflags    = "*"
bit_field   = "*"
x86_64      = "*"

[dependencies.lazy_static]
version = "*"
features = ["spin_no_std"]

[dependencies.rustos_common]
path = "rustos_common"

[dependencies.hole_tracking_allocator]
path = "hole_tracking_allocator"
