[workspace]

[package]
name = "kernel"
version = "0.0.1"
authors = ["Isaac Woods"]

[dependencies]
volatile    = "*"
spin        = "*"
bitflags    = "*"
bit_field   = "*"

[dependencies.log]
version             = "*"
default-features    = false

[dependencies.arch]
path = "arch"
