[package]
name = "cargo-pebble"
version = "0.0.0"
authors = ["Isaac Woods"]
description = "A Cargo subcommand to manage Pebble distributions"
repository = "https://github.com/pebble-os/pebble/cargo-pebble"
keywords = ["pebble", "cargo", "build"]
license = "MIT"
edition = "2018"

[dependencies]
