[package]
name = "hole_tracking_allocator"
version = "0.1.0"
authors = ["Isaac Woods <isaacwoods.home@gmail.com>"]

[dependencies]
spin = "*"

[dependencies.log]
version                 = "*"
default-features        = false

[dependencies.kernel]
path = ".."
